/* Map of task id → illustration PNG path.
   Generated by generate_illustrations.py — re-run that script to refresh.
   PNGs live in ./illustrations/<id>.png at 1200x720. */
const ILLUSTRATIONS = {
  'fence-paling':       'illustrations/fence-paling.png',
  'deck-build':         'illustrations/deck-build.png',
  'weatherboards':      'illustrations/weatherboards.png',
  'cutting-trims':      'illustrations/cutting-trims.png',
  'gibbing':            'illustrations/gibbing.png',
  'plastering':         'illustrations/plastering.png',
  'hang-door':          'illustrations/hang-door.png',
  'painting':           'illustrations/painting.png',
  'tiling-splashback':  'illustrations/tiling-splashback.png',
  'shelves':            'illustrations/shelves.png',
  'flat-pack':          'illustrations/flat-pack.png',
  'plasterboard-patch': 'illustrations/plasterboard-patch.png',
  'caulking':           'illustrations/caulking.png',
  'hanging-pictures':   'illustrations/hanging-pictures.png',
  'curtain-rails':      'illustrations/curtain-rails.png',
  'sand-finish':        'illustrations/sand-finish.png',
  'fence-gate':         'illustrations/fence-gate.png',
  'raised-garden-bed':  'illustrations/raised-garden-bed.png',
  'sharpen-tools':      'illustrations/sharpen-tools.png'
};
